# Generated by Django 3.1.5 on 2021-01-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinoman', '0002_auto_20210114_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fees_in_world',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Сборы в мире'),
        ),
    ]
