# Generated by Django 3.1.5 on 2021-01-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinoman', '0004_auto_20210125_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country_en',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country_ru',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tagline_en',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tagline_ru',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='movieshots',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='movieshots',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='movieshots',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='movieshots',
            name='title_ru',
        ),
    ]
